- Cargo.lock
- Cargo.toml
- src/lib.rs
Before, link titles that contained quotes would be rendered without their interior quotes escaped and preprocessing would turn
```md
[link](dest "\"weird title\"")
```
into
```md
[link](dest ""weird title"")
```
resulting in a broken link.
This was due to a bug in `pulldown-cmark-to-cmark` fixed in https://github.com/Byron/pulldown-cmark-to-cmark/pull/62 and released in version 11.0.2, so this PR bumps the version requirement.
> fix: escape quotes within link titles

- Cargo.toml
Prevents `cargo package` from including unnecessary files, in particular the `books` subdirectory
> chore: explicitly include files for cargo packaging

- .github/workflows/release.yml
- Cargo.toml
The `rust-cache` action in the release workflow currently breaks because this repo's submodules contain a lot of `Cargo.toml` and `Cargo.lock` files. This will be fixed by https://github.com/Swatinem/rust-cache/pull/180, but for now this PR disables cloning submodules during the release workflow.
> Fix release workflow

- src/lib.rs
- src/preprocess.rs
- src/snapshots/mdbook_pandoc__tests__nomicon.snap
- src/snapshots/mdbook_pandoc__tests__rust_by_example.snap
Strips [mdBook attributes](https://rust-lang.github.io/mdBook/format/mdbook.html#rust-code-block-attributes) from Rust code blocks so they are interpreted as Rust code blocks by pandoc.
> Syntax highlighting for Rust code blocks with mdBook attributes

- src/preprocess.rs
- src/snapshots/mdbook_pandoc__tests__mdbook_guide.snap
- src/snapshots/mdbook_pandoc__tests__rust_embedded.snap
- src/snapshots/mdbook_pandoc__tests__rustc_dev_guide.snap
Separators (see [here](https://rust-lang.github.io/mdBook/format/summary.html#structure)) are used only to render lines dividing the table of contents. We may want to do something with them in the future, but ignoring them isn't particularly important to report
> Decrease log level of ignored separator warning to DEBUG

- Cargo.lock
- Cargo.toml
- README.md
- src/lib.rs
- src/preprocess.rs
Closes #18
> Pandoc currently doesn't support using URLs with paths that do not have standard image extensions (e.g. `.png`, `.svg`) as image destinations.
>
> For example, pandoc will not process the following GitHub actions badge from [shields.io](https://shields.io):
> ```md 
> ![Build](https://img.shields.io/github/actions/workflow/status/max-heller/mdbook-pandoc/ci.yml?style=flat-square) 
> ```
This implements a heuristic fix to download images that pandoc is known not to support.
> Download remote images that pandoc doesn't handle on its own

- Cargo.toml
This doesn't seem to effect `cargo-dist`-generated installers right now, but hopefully it will someday
> Specify `pandoc` and `rsvg-convert` as dependencies in `cargo-dist` config

- src/lib.rs
- src/preprocess.rs
- src/snapshots/mdbook_pandoc__tests__cargo_book.snap
- src/snapshots/mdbook_pandoc__tests__rust_book.snap
- src/snapshots/mdbook_pandoc__tests__rust_embedded.snap
- src/snapshots/mdbook_pandoc__tests__rust_reference.snap
- src/snapshots/mdbook_pandoc__tests__rustc_dev_guide.snap
Sets the working directory for `pandoc` to the mdBook root directory instead of the destination directory, which makes more sense when passing filenames to Pandoc through options like [`--include-in-header`](https://pandoc.org/MANUAL.html#option--include-in-header).
> Run `pandoc` with mdBook root as working directory

- Cargo.toml
- README.md
- scripts/cargo-dist-render-books
- src/latex.rs
- src/lib.rs
- src/pandoc.rs
- src/pandoc/renderer.rs
- src/preprocess.rs
- src/snapshots/mdbook_pandoc__tests__rustc_dev_guide.snap
LaTeX by default can't handle lists with more than four levels of items. If necessary to render the book, this adds a dependency on the `enumitem` package to support more nested lists.
> Support lists nested more than four levels deep when rendering to LaTeX

- Cargo.lock
- Cargo.toml
- README.md
- src/lib.rs
- src/pandoc/profile.rs
- src/pandoc/renderer.rs
As a result, some options must be specified with different names--in particular, `output` becomes `output-file`
> Pass options to Pandoc as defaults file instead of command-line arguments

- .github/workflows/release.yml
- Cargo.toml
This includes https://github.com/Swatinem/rust-cache/pull/180 and allows using the unmodified `cargo-dist` release workflow
> ci: update `cargo-dist` to v0.7.1

- src/lib.rs
- src/preprocess.rs
- src/snapshots/mdbook_pandoc__tests__cargo_book.snap
- src/snapshots/mdbook_pandoc__tests__rust_book.snap
- src/snapshots/mdbook_pandoc__tests__rust_reference.snap
- src/snapshots/mdbook_pandoc__tests__rustc_dev_guide.snap
Fixes chapter numbering in the presence of prefix/suffix chapters and multiple top-level headings per chapter
> fix: correctly number chapters

- Cargo.lock
- Cargo.toml
- README.md
- src/lib.rs
- src/pandoc/extension.rs
- src/pandoc/filters/annotate-tables-with-column-widths.lua
- src/pandoc/profile.rs
- src/pandoc/renderer.rs
- src/preprocess.rs
- src/snapshots/mdbook_pandoc__tests__cargo_book.snap
- src/snapshots/mdbook_pandoc__tests__rust_book.snap
- src/snapshots/mdbook_pandoc__tests__rust_embedded.snap
- src/snapshots/mdbook_pandoc__tests__rust_reference.snap
- src/snapshots/mdbook_pandoc__tests__rustc_dev_guide.snap
Emulates [Pandoc's cell-wrapping behavior for tables](https://pandoc.org/MANUAL.html#extension-pipe_tables) to prevent wide tables from overflowing the page
> feat: wrap cells of wide tables

- Cargo.lock
- Cargo.toml
- src/lib.rs
- src/pandoc/renderer.rs
- src/preprocess.rs
- src/snapshots/mdbook_pandoc__tests__cargo_book.snap
- src/snapshots/mdbook_pandoc__tests__rust_book.snap
- src/snapshots/mdbook_pandoc__tests__rust_embedded.snap
- src/snapshots/mdbook_pandoc__tests__rust_reference.snap
- src/snapshots/mdbook_pandoc__tests__rustc_dev_guide.snap
Uses the [`fvextra` package](https://mirror.mwt.me/ctan/macros/latex/contrib/fvextra/fvextra.pdf) to enable line wrapping in code blocks in LaTeX books.
TODO:
Resolved by wrapping really long lines in `\texttt{}`
Resolved by replacing empty infostrings with "text"
> feat: wrap long lines in code blocks

- Cargo.lock
- Cargo.toml
- Update `regex` version requirement to avoid [security advisory](https://rustsec.org/advisories/RUSTSEC-2022-0013.html)
- Update `pulldown-cmark-to-cmark` to 13.0.0
- Update `toml` to 0.8
> chore(deps): update `pulldown-cmark-to-cmark`, `toml`, and `regex` dependencies

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
* `mdbook-pandoc`: 0.6.1 -> 0.6.2
<blockquote>
- Improve rendering of example books ([#79](https://github.com/max-heller/mdbook-pandoc/pull/79))
</blockquote>
</p></details>
---
This PR was generated with [release-plz](https://github.com/MarcoIeni/release-plz/).
> chore: release v0.6.2

- src/lib.rs
- src/pandoc.rs
- src/pandoc/extension.rs
- src/pandoc/renderer.rs
> fix: correctly parse `pandoc` versions with fewer than three components

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
* `mdbook-pandoc`: 0.6.2 -> 0.6.3
<blockquote>
- Correctly parse `pandoc` versions with fewer than three components ([#82](https://github.com/max-heller/mdbook-pandoc/pull/82))
</blockquote>
</p></details>
---
This PR was generated with [release-plz](https://github.com/MarcoIeni/release-plz/).
> chore: release v0.6.3

- Cargo.lock
- Cargo.toml
- src/book.rs
- src/lib.rs
- src/pandoc/renderer.rs
- src/preprocess.rs
On Windows, `std::fs::canonicalize()` [produces a weird type of path that cannot be used with `Command::current_dir()`](https://github.com/rust-lang/rust/issues/42869). This switches to using the [`normpath`](https://docs.rs/normpath/latest/normpath/trait.PathExt.html#tymethod.normalize) crate, which should avoid these issues.
> fix(windows): normalize paths with `normpath` instead of `std::fs::canonicalize()`

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
* `mdbook-pandoc`: 0.6.3 -> 0.6.4
<blockquote>
- Normalize paths with `normpath` instead of `std::fs::canonicalize()` ([#84](https://github.com/max-heller/mdbook-pandoc/pull/84))
</blockquote>
</p></details>
---
This PR was generated with [release-plz](https://github.com/MarcoIeni/release-plz/).
> chore: release v0.6.4

- README.md
- src/pandoc.rs
Defaults files (`--defaults`/`-d`) were introduced in [2.8](https://pandoc.org/releases.html#pandoc-2.8-2019-11-22)
> fix(docs): minimum `pandoc` version is actually 2.8, not 1.14

- Cargo.lock
- Cargo.toml
- src/lib.rs
- src/preprocess.rs
Using https://github.com/Byron/pulldown-cmark-to-cmark/pull/71, attempts to preserve escape characters (or lack thereof) from the Markdown source, e.g. keeping ``[`Vec`]`` as ``[`Vec`]`` and ``\[`Vec`\]`` as ``\[`Vec`\]``.
Closes #91
> feat: preserve escape characters (or lack thereof) from Markdown source

- Cargo.lock
- Cargo.toml
- README.md
- src/lib.rs
- src/pandoc.rs
- src/pandoc/profile.rs
- src/pandoc/renderer.rs
If `from` is set in a profile, respect the format and extensions it implies. For example, if `from = commonmark-gfm_auto_identifiers`, `mdbook-pandoc` will disable `gfm_auto_identifiers` event if it otherwise would have enabled it. Fixes #97
> feat: allow overriding source format and extensions through Pandoc's `from` option

- .github/workflows/ci.yml
- src/lib.rs
- src/pandoc/renderer.rs
Pandoc's `--file-scope` option [only takes effect if there are at least two files](https://pandoc.org/MANUAL.html#option--file-scope[), so if there is only one file, links will not be adjusted correctly. In this case, add an additional empty dummy file as input to convince Pandoc to perform the link adjustment.
> fix: resolve links correctly when book contains exactly one chapter

- src/lib.rs
- src/preprocess.rs
- src/snapshots/mdbook_pandoc__tests__rustc_dev_guide.snap
If a book contains `chapter.md` at the top-level, a link like `[link](/chapter.md]` should point to that chapter. This fixes `mdbook-pandoc`'s handling of such links
> fix: correctly resolve absolute-path links to be relative to book root

- src/lib.rs
I tried the new version of `mdbook-pandoc`, and found that it fails on my laptop which didn't have `pandoc` installed.
> Check for `disabled = true` before invoking `pandoc`

- src/lib.rs
- src/preprocess.rs
> fix: keep inline HTML inline

- src/preprocess.rs
I have a book layout that looks as:
- book.toml
- foo.md
- bar/bar.md
That results in an infinite recursion while copying the files to the "book/pdf" destination directory as that directory repeatedly get copied into itself.
The attached patch fixes this by checking if the file to be copied is within the destination directory and skipping it accordingly.
> Fix infinite recursion in Preprocessor when book.toml is next to book destination

- Cargo.lock
- Cargo.toml
- src/css.rs
- src/lib.rs
- src/pandoc/profile.rs
- src/pandoc/renderer.rs
- src/preprocess.rs
Parses `<img>` tags from raw HTML and converts them to Markdown image tags that Pandoc will process in non-HTML output formats. Also supports basic image styling from `width`/`height`/`style` attributes and CSS stylesheets since the Rust book relies on this.
> feat!: support `<img>` tags

- src/lib.rs
- src/pandoc/profile.rs
- src/pandoc/renderer.rs
Previously, document metadata (title, authors, etc.) was only set for LaTeX documents. This change sets this metadata for all output formats, and properly sets some of the variables as [`metadata` variables](https://pandoc.org/MANUAL.html#metadata-variables) instead of [regular `variables`](https://pandoc.org/MANUAL.html#language-variables).
> fix: set document metadata for all output formats

- src/lib.rs
- src/pandoc/renderer.rs
- src/snapshots/mdbook_pandoc__tests__cargo_book.snap
- src/snapshots/mdbook_pandoc__tests__mdbook_guide.snap
- src/snapshots/mdbook_pandoc__tests__nomicon.snap
- src/snapshots/mdbook_pandoc__tests__rust_book.snap
- src/snapshots/mdbook_pandoc__tests__rust_by_example.snap
- src/snapshots/mdbook_pandoc__tests__rust_edition_guide.snap
- src/snapshots/mdbook_pandoc__tests__rust_embedded.snap
- src/snapshots/mdbook_pandoc__tests__rust_reference.snap
- src/snapshots/mdbook_pandoc__tests__rustc_dev_guide.snap
Decreases the log level for processing redirects and increases the log level for running pandoc so it's clear that Pandoc is what's dominating the runtime of a build.
Previously:
```
INFO mdbook_pandoc: Processing redirects in [output.html.redirect]
DEBUG mdbook_pandoc::pandoc::renderer: Running pandoc
```
Now:
```
DEBUG mdbook_pandoc: Processing redirects in [output.html.redirect]
INFO mdbook_pandoc::pandoc::renderer: Running pandoc
```
> change: tweak log levels to better convey where time is spent

- Cargo.lock
- Cargo.toml
- src/html.rs
- src/lib.rs
- src/pandoc/native.rs
- src/preprocess.rs
- src/preprocess/tree.rs
- src/preprocess/tree/node.rs
- src/preprocess/tree/sink.rs
Parses each Markdown file into a DOM-like tree using a browser-grade HTML parser to ensure that implicit structure present in raw HTML is preserved.
> change: construct a combined Markdown+HTML tree

- src/lib.rs
- src/pandoc/native.rs
- src/preprocess/tree.rs
- src/preprocess/tree/node.rs
When HTML elements remain unclosed at the end of a raw HTML block, we sometimes wrap the contents of the element in a <div> to preserve the implicit structure when converting to e.g. EPUB for which Pandoc breaks documents into sections based on inferred structure.
The old behavior was too aggressive and resulted in unintended line breaks because pandoc has no notion of inline divs. This change refines the heuristic to be more selective.
> fix!: be more selective about div-wrapping

- src/lib.rs
- src/preprocess.rs
- src/preprocess/code.rs
- src/preprocess/tree.rs
Implements line hiding in Rust code blocks [as specified in the rustdoc book](https://doc.rust-lang.org/rustdoc/write-documentation/documentation-tests.html#hiding-portions-of-the-example). MDBook has a slightly different implementation but claims to mirror rustdoc so we treat rustdoc as the authority.
> fix: correctly hide lines in Rust code blocks

- src/lib.rs
- src/pandoc/native.rs
- src/preprocess.rs
- src/preprocess/tree.rs
Pandoc does not support cyclic footnote definitions so trying to write the AST for one results in infinite recursion and a stack overflow. Adds a check to detect this before the stack overflow and emit a warning.
> fix: detect cycles in footnote definitions

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
* `mdbook-pandoc`: 0.9.1 -> 0.9.2
<blockquote>
- Parse `<noscript>` elements without panicking (#150)
- Detect cycles in footnote definitions (#151)
</blockquote>
</p></details>
---
This PR was generated with [release-plz](https://github.com/release-plz/release-plz/).
> chore: release v0.9.2

- README.md
crates.io does not support GitHub's block quote alert syntax.
> doc: suggest `cargo install --locked` and fix formatting

- .gitmodules
- scripts/install-ci-deps
Ensures `cargo install --git` doesn't checkout the submodules, which are only used in tests. See https://github.com/rust-lang/cargo/pull/10717
> chore: set `update=none` for example book submodules

- Cargo.lock
- Cargo.toml
- scripts/install-ci-deps
- src/preprocess.rs
- src/preprocess/tree.rs
- src/tests/images.rs
Removes a workaround for remote images served from URIs without standard
image extensions (e.g., https://img.shields.io/github/actions/workflow/status/rust-lang/mdBook/main.yml
hosts an SVG image despite its YAML extension) since Pandoc implemented
a fix in https://github.com/jgm/pandoc/pull/10557 (released in 3.6.3).
This allows removing the dependency on an HTTP client.
> change!: do not attempt to download remote images

- Cargo.lock
- Cargo.toml
- src/preprocess.rs
Upgrades `pulldown-cmark` from 0.10.0 to 0.13.0, diverging from mdbook which is stuck on 0.10.0. The new extensions are left disabled, so this shouldn't be a breaking change.
> change: upgrade `pulldown-cmark` to 0.13.0

- README.md
- src/lib.rs
- src/pandoc/profile.rs
- src/preprocess.rs
- src/preprocess/tree.rs
- src/preprocess/tree/node.rs
- src/tests/alerts.rs
- src/tests/html.rs
- src/tests/mod.rs
Needs an upgrade to `pulldown-cmark`, so will wait to merge until `mdbook` releases a breaking change (see #115).
Closes #117 although not in a terribly helpful way since it appears Pandoc doesn't do anything with alerts when generating LaTeX:
```
$ echo '> [!NOTE]\n> Highlights information that users should take into account, even when skimming.' | pandoc -f commonmark+alerts -t latex
Note
Highlights information that users should take into account, even when
skimming.
```
Contrast with:
```
$ echo '> Highlights information that users should take into account, even when skimming.' | pandoc -f commonmark+alerts -t latex
\begin{quote}
Highlights information that users should take into account, even when
skimming.
\end{quote}
```
> feat: support block quote tags e.g. [!NOTE]

- README.md
- src/lib.rs
- src/pandoc/native.rs
- src/preprocess.rs
- src/preprocess/tree.rs
- src/preprocess/tree/node.rs
- src/tests/math.rs
- src/tests/mod.rs
Adds support for inline and block-level mathematical expressions using `$a^b$` and `$$a^b$$`. For consistency with mdbook, this feature is disabled by default and must be explicitly enabled by enabling the `output.pandoc.markdown.extensions.math` option.
> feat: support mathematical expressions

- README.md
- src/lib.rs
- src/pandoc/native.rs
- src/preprocess.rs
- src/preprocess/tree.rs
- src/preprocess/tree/node.rs
- src/tests/definition_lists.rs
- src/tests/mod.rs
Adds support for definition lists. For consistency with mdbook, this feature is disabled by default and must be explicitly enabled with the `output.pandoc.markdown.extensions.definition-lists` option.
```markdown
term 1
: definition 1
term 2
: definition 2 a
: definition 2 b
```
> feat: support definition lists

- Cargo.lock
- Cargo.toml
- src/main.rs
```
2025-02-15 09:33:51 [INFO] (mdbook::book): Book building has started
2025-02-15 09:33:51 [INFO] (mdbook::book): Running the html backend
2025-02-15 09:33:51 [INFO] (mdbook::book): Running the pandoc backend
2025-02-15 09:33:51 [INFO] (mdbook::renderer): Invoking the "pandoc" renderer
2025-02-15 09:33:51 [INFO] (mdbook_pandoc::pandoc::renderer): Running pandoc
2025-02-15 09:33:53 [INFO] (mdbook_pandoc::pandoc::renderer): Wrote output to book/pandoc/pdf/book.pdf
```
> change: match mdbook's log format

- README.md
- src/lib.rs
- src/pandoc/native.rs
- src/preprocess.rs
- src/preprocess/tree.rs
- src/preprocess/tree/node.rs
- src/tests/html.rs
- src/tests/mod.rs
- src/tests/super_sub.rs
Adds support for superscripted and subscripted text. For consistency with mdbook, these features are disabled by default and must be enabled with the `output.pandoc.markdown.extensions.superscript` and `output.pandoc.markdown.extensions.subscript` options.
This change also adds support for `<sup>` and `<sub>` HTML elements, which does not require enabling the aforementioned config options.
```markdown
^This is superscripted^ ~This is subscripted~
```
> feat: support superscripted and subscripted text

- src/preprocess.rs
- src/tests/math.rs
When `output.html.mathjax-support = true`, parses the following patterns as mathematical expressions and renders them using Pandoc's math nodes:
- InlineMath:  `\\(...\\)`
- DisplayMath: `\\[...\\]` and `$$...$$`
Note: pulldown-cmark's math extension (`$...$` and `$$...$$`), enabled by `output.pandoc.markdown.extensions.math = true`, takes precedence over this mathjax emulation. Parsing behavior is slightly different between the two--in particular, a line break is `\\` in the pulldown-cmark variant, whereas it must be written as `\\\\` in the mathjax variant.
> feat: emulate HTML renderer's mathjax support

- src/preprocess/code.rs
- src/preprocess/tree.rs
- src/tests/code.rs
- src/tests/mod.rs
For a code block like
````
```rust,compile_fail
fn main() {
doesnotexist();
}
```
````
mdbook-pandoc would previously create a Pandoc CodeBlock with just a "rust" class. Now, "compile_fail" and other attributes are added to the list of classes as well to allow for custom styling.
Closes #184
> feat: add code block attributes as additional classes

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
* `mdbook-pandoc`: 0.10.2 -> 0.10.3
<blockquote>
- Correctly generate TOC when nested chapters don't contain H1s (#182)
- Add code block attributes as additional classes (#185)
</blockquote>
</p></details>
---
This PR was generated with [release-plz](https://github.com/release-plz/release-plz/).
> chore: release v0.10.3

- Cargo.lock
- Cargo.toml
- src/latex.rs
- src/lib.rs
- src/pandoc/native.rs
- src/preprocess.rs
- src/preprocess/tree.rs
- src/preprocess/tree/node.rs
- src/tests/math.rs
- src/tests/mod.rs
To better emulate MathJax, allows using TeX macros that are defined in one math inline/block from other math inlines/blocks.
> feat: support using TeX macros across math inlines/blocks 

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
* `mdbook-pandoc`: 0.10.3 -> 0.10.4
<blockquote>
- Correctly parse multiline $$-delimited MathJax math (#186)
- Support using TeX macros across math inlines/blocks  (#188)
</blockquote>
</p></details>
---
This PR was generated with [release-plz](https://github.com/release-plz/release-plz/).
> chore: release v0.10.4

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
* `mdbook-pandoc`: 0.10.4 -> 0.10.5
<blockquote>
- Don't panic on empty tables ([#190](https://github.com/max-heller/mdbook-pandoc/pull/190))
</blockquote>
</p></details>
---
This PR was generated with [release-plz](https://github.com/release-plz/release-plz/).
> chore: release v0.10.5

- README.md
- src/lib.rs
- src/tests/books.rs
- src/tests/links.rs
- src/tests/mod.rs
`output.pandoc.hosted_html` is redundant with `output.html.site-url`; consider the latter but continue supporting the former to avoid breakage
> feat: Consider `output.html.site-url` when replace broken relative links
